pyadjoint
fireshape/fireshape pull request #36
Opened 2019-04-26 14:38 UTC by florianwechsung

- We now use pyadjoint to calculate adjoints and shape derivatives when there are pde constraints
This enabled a couple of simplications across the code, so I went through examples and some tests and cut out some unneeded bits

- Changed `update_domain(self, q)` in `control.py` to check whether the domain has actually changed 

- changed circleci to run the levelset and the l2tracking example. should at some point probably run all examples, or at least the quick ones

2019-04-26 15:15 UTC, florianwechsung commented
once this is merged I will update the pipe code to make use of pyadjoint and then I think we can merge the pipe as well.

2019-04-29 10:55 UTC, APaganini requested changes

2019-04-29 10:55 UTC, APaganini commented on fireshape/objective.py
> +        fda.pause_annotation()
please add comment

2019-05-21 14:34 UTC, APaganini approved these changes

2019-05-21 14:40 UTC, merged